//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancel_timetable
    {
        public int cid { get; set; }
        public string Teacher { get; set; }
        public string Class { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time { get; set; }
        public string years { get; set; }
        public string months { get; set; }
        public string days { get; set; }
        public string employee { get; set; }
        public string type { get; set; }
        public string status { get; set; }
    }
}
