//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int SystemID { get; set; }
        public string ClassID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UpdateByUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
