//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSubject
    {
        public int SystemID { get; set; }
        public string ClassSubjectID { get; set; }
        public string ClassID { get; set; }
        public string SubjectID { get; set; }
        public string TeacherId { get; set; }
        public Nullable<decimal> SubjectFee { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UpdateByUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string InstituteID { get; set; }
        public string Branch { get; set; }
    }
}
