//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySummery
    {
        public int DailySummeryId { get; set; }
        public Nullable<System.DateTime> SummeryDate { get; set; }
        public Nullable<decimal> CashInHand { get; set; }
        public Nullable<decimal> SubjectFeeThisMonth { get; set; }
        public Nullable<decimal> SubjectFeePrevious { get; set; }
        public Nullable<decimal> MaintenanceFee { get; set; }
        public Nullable<decimal> AddminFee { get; set; }
        public Nullable<decimal> OtherCollection { get; set; }
        public Nullable<decimal> TeacherSalary { get; set; }
        public Nullable<decimal> OthersSalary { get; set; }
        public bool IsDeleted { get; set; }
        public string ErrorNote { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> ComputerId { get; set; }
        public Nullable<decimal> StudentAdvance { get; set; }
        public Nullable<decimal> UsedAdvance { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Branch { get; set; }
    }
}
