//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultValue
    {
        public int SystemID { get; set; }
        public Nullable<float> PerOfTeacherPay { get; set; }
        public Nullable<decimal> MaitanenceFee { get; set; }
        public string Company { get; set; }
        public string OwenerId { get; set; }
        public Nullable<short> MachineId { get; set; }
        public string MachineName { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<short> fontSize { get; set; }
        public Nullable<System.DateTime> LastProcessedDate { get; set; }
        public Nullable<System.DateTime> LastWorkedDate { get; set; }
        public Nullable<System.DateTime> SummeryPrintedDate { get; set; }
        public bool IsOpened { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public bool HasNewTransaction { get; set; }
        public string OwnerEmail { get; set; }
    }
}
