//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentID
    {
        public int SysID { get; set; }
        public string EnrollmentID1 { get; set; }
        public string InstituteID { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string Branch { get; set; }
    }
}
