//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetail
    {
        public int ExpenseDetailID { get; set; }
        public System.DateTime Dates { get; set; }
        public int ExpenseID { get; set; }
        public string Account { get; set; }
        public string PayMode { get; set; }
        public decimal Amount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal Balance { get; set; }
        public string PNumber { get; set; }
        public string PayTo { get; set; }
        public string Memo { get; set; }
        public string ExpenseFrom { get; set; }
        public string Branch { get; set; }
        public string Descriptions { get; set; }
    }
}
