//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpenseID { get; set; }
        public string Descriptions { get; set; }
        public string Deductible { get; set; }
    }
}
