//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favor
    {
        public int FavorID { get; set; }
        public string StudentID { get; set; }
        public string IstituteID { get; set; }
        public Nullable<int> SubjectCount { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Branch { get; set; }
    }
}
