//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nobleEntities : DbContext
    {
        public nobleEntities()
            : base("name=nobleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassSubject> ClassSubjects { get; set; }
        public virtual DbSet<ClassType> ClassTypes { get; set; }
        public virtual DbSet<DailySummery> DailySummeries { get; set; }
        public virtual DbSet<DefaultValue> DefaultValues { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EnrollmentID> EnrollmentIDS { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<ExpenseDetail> ExpenseDetails { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<Favor> Favors { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<Institute> Institutes { get; set; }
        public virtual DbSet<OD_Employees> OD_Employees { get; set; }
        public virtual DbSet<Stu_TempReg> Stu_TempReg { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentAttendance> StudentAttendances { get; set; }
        public virtual DbSet<StudentClass> StudentClasses { get; set; }
        public virtual DbSet<StudentDue> StudentDues { get; set; }
        public virtual DbSet<StudentEnrollment> StudentEnrollments { get; set; }
        public virtual DbSet<StudentIndenty> StudentIndenties { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<TeacherPaymentSummery> TeacherPaymentSummeries { get; set; }
        public virtual DbSet<Teachers_Attendance> Teachers_Attendance { get; set; }
        public virtual DbSet<tempLecturer> tempLecturers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransNote> TransNotes { get; set; }
        public virtual DbSet<CardTemplate> CardTemplates { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<Paste_Error> Paste_Errors { get; set; }
        public virtual DbSet<PaymentCatergory> PaymentCatergories { get; set; }
        public virtual DbSet<temp_EX_Student> temp_EX_Student { get; set; }
        public virtual DbSet<tempStEnrolToDelete> tempStEnrolToDeletes { get; set; }
        public virtual DbSet<tempStSubfee> tempStSubfees { get; set; }
        public virtual DbSet<temptran> temptrans { get; set; }
        public virtual DbSet<trandToDelete> trandToDeletes { get; set; }
        public virtual DbSet<cancel_timetable> cancel_timetable { get; set; }
        public virtual DbSet<Event> Events { get; set; }
    }
}
