//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCatergory
    {
        public string CategoryID { get; set; }
        public string Category { get; set; }
        public decimal Amount { get; set; }
        public Nullable<short> SortOrder { get; set; }
    }
}
