//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu_TempReg
    {
        public int TRID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string StuMobile { get; set; }
        public string ParentsMobile { get; set; }
        public string School { get; set; }
        public string Grade { get; set; }
        public string ParentsID { get; set; }
        public string Email { get; set; }
        public string Religion { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string ReferenceCode { get; set; }
        public string Status { get; set; }
        public string Address1 { get; set; }
        public string ParentJob { get; set; }
        public string OldStudents { get; set; }
    }
}
