//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int Stu_EntryID { get; set; }
        public string StudentID { get; set; }
        public string InstituteID { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string Time { get; set; }
        public string ClassSubjectID { get; set; }
        public string SubjectID { get; set; }
        public string EmployeeID { get; set; }
        public string Status { get; set; }
        public string Month { get; set; }
        public string Branch { get; set; }
    }
}
