//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int SystemID { get; set; }
        public string StudentID { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public Nullable<short> IdentificationType { get; set; }
        public string IdentificationNo { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string AddressLine { get; set; }
        public string AddressLine1 { get; set; }
        public string StuMobile { get; set; }
        public string ParentsMobile { get; set; }
        public string ParentsID { get; set; }
        public string School { get; set; }
        public string Grade { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UpdateByUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> HouseId { get; set; }
        public string emailAddress { get; set; }
        public Nullable<short> MachineId { get; set; }
        public string InstituteID { get; set; }
        public string Religion { get; set; }
        public byte[] Photo { get; set; }
        public string OldStudent { get; set; }
        public string Category { get; set; }
        public string Wishes { get; set; }
        public byte[] Doc { get; set; }
        public string Branch { get; set; }
    }
}
