//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDue
    {
        public int StudentDueID { get; set; }
        public string ClassSubjectID { get; set; }
        public string ClassID { get; set; }
        public string SubjectID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Due { get; set; }
        public string Teacherid { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string Month { get; set; }
        public string Status { get; set; }
        public string InstituteID { get; set; }
        public string Branch { get; set; }
    }
}
