//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEnrollment
    {
        public int SystemID { get; set; }
        public string EntrollmentID { get; set; }
        public string StudentID { get; set; }
        public string ClassSubjectID { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public Nullable<float> PercentageOfFee { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UpdateByUser { get; set; }
        public Nullable<short> MachineId { get; set; }
        public string Teacherid { get; set; }
        public string InstituteID { get; set; }
        public bool Checked { get; set; }
        public string Branch { get; set; }
    }
}
