//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherPaymentSummery
    {
        public int TeacherSummeryId { get; set; }
        public string TeacherCode { get; set; }
        public Nullable<System.DateTime> SummeryDate { get; set; }
        public string ClassSubjectID { get; set; }
        public string CategoryCode { get; set; }
        public Nullable<decimal> TeacherAmount { get; set; }
        public Nullable<decimal> StudentPayment { get; set; }
        public Nullable<int> NoOfStudent { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> UnitAmount { get; set; }
        public Nullable<int> ComputerId { get; set; }
        public string BillID { get; set; }
        public string Month { get; set; }
        public string InstituteID { get; set; }
        public string EntrollmentID { get; set; }
        public string Branch { get; set; }
        public string Year { get; set; }
    }
}
