//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int SystemID { get; set; }
        public string TransactionID { get; set; }
        public string StudentID { get; set; }
        public string EmployeeID { get; set; }
        public string InstituteID { get; set; }
        public string Reference { get; set; }
        public string BillID { get; set; }
        public string CategoryCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<short> noOfItems { get; set; }
        public bool IsSettled { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UpdateByUser { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string MachineId { get; set; }
        public string Category { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Status { get; set; }
        public string Month { get; set; }
        public string EntrollmentID { get; set; }
        public string Branch { get; set; }
    }
}
